name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page:num/"
permalink: /blog/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html 
