title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com
