title: Erkin Filiz
description: 

url: https://erkinfiliz.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: ErkinFiliz
  twitter: realErkinFiliz
  #facebook: brianmaierjr
  email: flzerkin4@gmail.com
  linkedin: erkinfiliz

# google_analytics: "UA-58263416-1"

disqus:
    shortname: erkinfiliz
