title: 박정웅의 블로그
description: 평소 관심있는 분야, 코딩중 이슈 사항을 공유하는 공간입니다.

url: https://parkjungwoong.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: parkjungwoong
   email: myuoong@gmail.com

google_analytics: ""
