name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true
url: http://brianmaierjr.github.com/long-haul

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html 
