title: Wild People
description: Сайт который сделан сделан на Jekyll

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Главная
   url: /index.html
 - title: О сайте
   url: /about
 - title: Контакты
   url: /contact

social:
   github: WildPeople
   twitter:
   facebook:
   email: conrad.chernyatevich@gmail.com

google_analytics: "UA-88838263-1"


