title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
